### ISSUE TITLE
Can we have a review meeting?

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#21]
Hello Everyone,

I was thinking we should have a review meeting to see how far we are and planning on what to do next. Seems we have done a lot of work and I super proud of the engagement this project has gotten so far.

Which day works for you guys? I propose either today or tomorrow ( Wednesday 28th ). I couldn't find a way to contact all of you so I figured an issue will work. 

Kind regards, 
Katungi :-)

**Comment by Mogakamo** [comment]
@katungi today seems fine.

**Comment by Lekipising** [comment]
Today works for me

**Comment by 3stherMueni** [comment]
Hey @katungi  since we currently don't have a platform where we can reach everyone on time, I would suggest maybe Saturday so we can at least give everyone a chance to check out the discussion and see the meeting info. I would suggest Saturday in the evening, maybe 7 pm?

@VeldaKiara @TabithaKavyu , what are your thoughts?

**Comment by VeldaKiara** [comment]
8pm works for me

May the wombat of happiness snuffle through your underbrush,
Velda Kiara
Creative(Software) Engineer

**Comment by 3stherMueni** [comment]
Just set up the meeting: 
SCA Nairobi OS Challenge Review
Saturday, 2 July · 8:00 – 8:45pm
Google Meet joining info
Video call link: https://meet.google.com/jpv-qrxm-kjw

If you would like an invite personalized to your email, kindly DM scaNairobi on Twitter with your email.
